In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv( 'E:\\Python\\AML\\adult.csv' )
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.metrics import recall_score
from sklearn.model_selection import train_test_split

In [7]:
# попробуем выбрать какие-нибудь признаки
selectedColumns = data[ [ 'educational-num', 'race', 'marital-status', 'income' ] ]

# столбцы race и marital-status являются категориальными переменными
# переведем их в значения 0 и 1, добавив столбцы с соответствующими названиями
X = pd.get_dummies( selectedColumns, columns = [ 'race', 'marital-status'] )

# столбец sex является целевой переменной, удаляем его из X
del X['income']
X.head()

educational-num  race_Amer-Indian-Eskimo  race_Asian-Pac-Islander  \
0                7                        0                        0   
1                9                        0                        0   
2               12                        0                        0   
3               10                        0                        0   
4               10                        0                        0   

   race_Black  race_Other  race_White  marital-status_Divorced  \
0           1           0           0                        0   
1           0           0           1                        0   
2           0           0           1                        0   
3           1           0           0                        0   
4           0           0           1                        0   

   marital-status_Married-AF-spouse  marital-status_Married-civ-spouse  \
0                                 0                                  0   
1                                 0                                  1   
2                                 0                                  1   
3                                 0                                  1   
4                                 0                                  0   

   marital-status_Married-spouse-absent  marital-status_Never-married  \
0                                     0                             1   
1                                     0                             0   
2                                     0                             0   
3                                     0                             0   
4                                     0                             1   

   marital-status_Separated  marital-status_Widowed  
0                         0                       0  
1                         0                       0  
2                         0                       0  
3                         0                       0  
4                         0                       0

In [8]:
# целевая переменная (столбец income) снова является категориальной
# переведем значения столбца в числа, оставив один столбец

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [9]:
le.fit( data['income'] )

LabelEncoder()

In [10]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [11]:
# пример "расшировки" столбца income

le.transform( [ '<=50K', '>50K', '>50K' ] )

array([0, 1, 1], dtype=int64)

In [13]:
# записываем в переменную y преобразованный столбец income

y = pd.Series( data = le.transform( data['income'] ) )
y.head()

0    0
1    0
2    1
3    1
4    0
dtype: int32

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
model = LogisticRegression()

In [16]:
X_train

educational-num  race_Amer-Indian-Eskimo  race_Asian-Pac-Islander  \
43548               13                        0                        0   
27517                9                        0                        0   
13679                9                        0                        1   
45104                9                        0                        0   
14486                8                        0                        0   
...                ...                      ...                      ...   
39149                9                        0                        0   
29252                7                        0                        0   
6900                 9                        0                        0   
11321                9                        0                        0   
46056                9                        0                        0   

       race_Black  race_Other  race_White  marital-status_Divorced  \
43548           0           0           1                        0   
27517           0           0           1                        0   
13679           0           0           0                        0   
45104           0           0           1                        0   
14486           0           0           1                        0   
...           ...         ...         ...                      ...   
39149           0           0           1                        0   
29252           0           0           1                        0   
6900            0           0           1                        0   
11321           0           0           1                        1   
46056           0           0           1                        0   

       marital-status_Married-AF-spouse  marital-status_Married-civ-spouse  \
43548                                 0                                  1   
27517                                 0                                  0   
13679                                 0                                  0   
45104                                 0                                  1   
14486                                 0                                  0   
...                                 ...                                ...   
39149                                 0                                  1   
29252                                 0                                  0   
6900                                  0                                  1   
11321                                 0                                  0   
46056                                 0                                  1   

       marital-status_Married-spouse-absent  marital-status_Never-married  \
43548                                     0                             0   
27517                                     0                             1   
13679                                     0                             1   
45104                                     0                             0   
14486                                     0                             0   
...                                     ...                           ...   
39149                                     0                             0   
29252                                     0                             1   
6900                                      0                             0   
11321                                     0                             0   
46056                                     0                             0   

       marital-status_Separated  marital-status_Widowed  
43548                         0                       0  
27517                         0                       0  
13679                         0                       0  
45104                         0                       0  
14486                         1                       0  
...                         ...            

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [18]:
# обучаем модель

model.fit( X_train, y_train )
predictions = model.predict_proba( X_train )

In [19]:
predictions[:5]

array([[0.31136026, 0.68863974],
       [0.97703678, 0.02296322],
       [0.98285863, 0.01714137],
       [0.67947941, 0.32052059],
       [0.96816255, 0.03183745]])

In [22]:
model.predict(X_train)

array([1, 0, 0, ..., 0, 0, 0])

In [32]:
model.score(X_test, y_test)

0.246494011669567

In [25]:
model2 = svm.SVC(kernel='linear')

In [26]:
model2.fit( X_test, y_test )
predictions2 = model.predict_proba( X )

In [27]:
predictions2[:5]

array([[1.17362215e-02, 9.88263779e-01],
       [3.41772958e-04, 9.99658227e-01],
       [1.73562583e-05, 9.99982644e-01],
       [1.40593094e-04, 9.99859407e-01],
       [5.42480559e-04, 9.99457519e-01]])

In [30]:
model2.predict(X_train)

array([0, 0, 0, ..., 0, 0, 0])

In [31]:
model2.score(X_test, y_test)

0.8167673252124066