In [48]:
import pandas as pd
import numpy as np

In [49]:
data = pd.read_csv( 'E:\\Python\\AML\\adult.csv' )
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.metrics import recall_score

In [52]:
# попробуем выбрать какие-нибудь признаки
selectedColumns = data[ [ 'educational-num', 'race', 'marital-status', 'income' ] ]

# столбцы race и marital-status являются категориальными переменными
# переведем их в значения 0 и 1, добавив столбцы с соответствующими названиями
X = pd.get_dummies( selectedColumns, columns = [ 'race', 'marital-status'] )

# столбец sex является целевой переменной, удаляем его из X
del X['income']
X.head()

educational-num  race_Amer-Indian-Eskimo  race_Asian-Pac-Islander  \
0                7                        0                        0   
1                9                        0                        0   
2               12                        0                        0   
3               10                        0                        0   
4               10                        0                        0   

   race_Black  race_Other  race_White  marital-status_Divorced  \
0           1           0           0                        0   
1           0           0           1                        0   
2           0           0           1                        0   
3           1           0           0                        0   
4           0           0           1                        0   

   marital-status_Married-AF-spouse  marital-status_Married-civ-spouse  \
0                                 0                                  0   
1                                 0                                  1   
2                                 0                                  1   
3                                 0                                  1   
4                                 0                                  0   

   marital-status_Married-spouse-absent  marital-status_Never-married  \
0                                     0                             1   
1                                     0                             0   
2                                     0                             0   
3                                     0                             0   
4                                     0                             1   

   marital-status_Separated  marital-status_Widowed  
0                         0                       0  
1                         0                       0  
2                         0                       0  
3                         0                       0  
4                         0                       0

In [53]:
# целевая переменная (столбец income) снова является категориальной
# переведем значения столбца в числа, оставив один столбец

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [54]:
le.fit( data['income'] )

LabelEncoder()

In [55]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [56]:
# пример "расшировки" столбца income

le.transform( [ '<=50K', '>50K', '>50K' ] )

array([0, 1, 1], dtype=int64)

In [57]:
# записываем в переменную y преобразованный столбец income

y = pd.Series( data = le.transform( data['income'] ) )
y.head()

0    0
1    0
2    1
3    1
4    0
dtype: int32

In [58]:
model = LogisticRegression()

In [59]:
X

educational-num  race_Amer-Indian-Eskimo  race_Asian-Pac-Islander  \
0                    7                        0                        0   
1                    9                        0                        0   
2                   12                        0                        0   
3                   10                        0                        0   
4                   10                        0                        0   
...                ...                      ...                      ...   
48837               12                        0                        0   
48838                9                        0                        0   
48839                9                        0                        0   
48840                9                        0                        0   
48841                9                        0                        0   

       race_Black  race_Other  race_White  marital-status_Divorced  \
0               1           0           0                        0   
1               0           0           1                        0   
2               0           0           1                        0   
3               1           0           0                        0   
4               0           0           1                        0   
...           ...         ...         ...                      ...   
48837           0           0           1                        0   
48838           0           0           1                        0   
48839           0           0           1                        0   
48840           0           0           1                        0   
48841           0           0           1                        0   

       marital-status_Married-AF-spouse  marital-status_Married-civ-spouse  \
0                                     0                                  0   
1                                     0                                  1   
2                                     0                                  1   
3                                     0                                  1   
4                                     0                                  0   
...                                 ...                                ...   
48837                                 0                                  1   
48838                                 0                                  1   
48839                                 0                                  0   
48840                                 0                                  0   
48841                                 0                                  1   

       marital-status_Married-spouse-absent  marital-status_Never-married  \
0                                         0                             1   
1                                         0                             0   
2                                         0                             0   
3                                         0                             0   
4                                         0                             1   
...                                     ...                           ...   
48837                                     0                             0   
48838                                     0                             0   
48839                                     0                             0   
48840                                     0                             1   
48841                                     0                             0   

       marital-status_Separated  marital-status_Widowed  
0                             0                       0  
1                             0                       0  
2                             0                       0  
3                             0                       0  
4                             0                       0  
...                         ...            

In [60]:
# обучаем модель

model.fit( X, y )
predictions = model.predict_proba( X )

C:\Users\SD\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [61]:
predictions[:5]

array([[0.99217341, 0.00782659],
       [0.68029482, 0.31970518],
       [0.39667514, 0.60332486],
       [0.66489446, 0.33510554],
       [0.96598551, 0.03401449]])

In [62]:
# сравниваем факт с предсказаниями
# (да, сравнивать предсказания с самими данными не круто, лучше было разбить на обучающую и тестовую выборку)

zip( predictions[:, 1], y )

In [63]:
model.predict(X)

array([0, 0, 1, ..., 0, 0, 0])

In [64]:
model.score(X, y)

0.8187215920723967

In [65]:
model2 = svm.SVC(kernel='linear')

In [67]:
model2.fit( X, y )
predictions2 = model.predict_proba( X )

In [68]:
predictions2[:5]

array([[0.99217341, 0.00782659],
       [0.68029482, 0.31970518],
       [0.39667514, 0.60332486],
       [0.66489446, 0.33510554],
       [0.96598551, 0.03401449]])