In [9]:
import numpy as np
n = 10
np.arange(0, n)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [10]:
np.diag(np.arange(0, n)[::-1])

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
np.trace(np.diag(np.arange(0, n)[::-1]))

45

In [16]:
a = np.array([[4, 2, 1], [1, 3, 0], [5, 0, 4]])
b = np.array([4, 12, -3])
np.linalg.solve(a, b)

array([-1.56,  4.52,  1.2 ])